vae_model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128
  load_model: True
  pretrained_model: "checkpoints/vae.ckpt"
 
pix2pix_model_params:
  name: 'Pix2Pix GAN'
  gen_name: Generator
  disc_name: Discriminator
  load_model: True
  pretrained_model: "checkpoints/pix2pix.ckpt"


exp_params:
  dataset: terrain
  data_path: "/home/hdd/Documents/Terrain Authoring/terrain_datasets/terrain_contour_3k/"
  img_size: 256
  norm: 2
  n_workers: 8
  in_channels: 3
  out_channels: 3
  hide_green: False
  batch_size: 32 # Better to have a square number



logging_params:
  save_dir: "logs/"
  name: "VAE_PIX2PIX"
  manual_seed: 1563
