model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128

exp_params:
  dataset: terrain
  data_path: "../level_data/"
  img_size: 256
  norm: 0
  n_workers: 16
  hide_green: False
  batch_size: 64 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 200

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1563
